name: "Create dashboard"
on:
  schedule:
  - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::867686887310:role/sagebase-github-oidc-packer-image-deploy
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 600

      - name: Run AMI dashboard
        run: |
          python ami_dashboard.py

      - name: Commit report
        run: |
          git config --global user.name 'Image Central'
          git config --global user.email 'thomasyu888@users.noreply.github.com'
          git commit -am "Auto dashboard" || true
          # The above command will fail if no changes were present, so we ignore
          # that.
          git push

      # prevent GH action from disabling scheduled builds
      - uses: gautamkrishnar/keepalive-workflow@master
